set (ICU_LIBRARIES icui18n icuuc icudata)
target_compile_options(icui18n PRIVATE -Wno-unused -Werror)
target_compile_options(icuuc PRIVATE -Wno-unused -Werror)
target_compile_options(icudata PRIVATE -Wno-unused -Werror)
set (ICU_INCLUDE_DIR "${XMorphy_SOURCE_DIR}/contrib/icu/icu4c/source/common")
